### ISSUE TITLE
[BUG] Preview in Iframe mode only shows content-areas

### ISSUE THREAD

**Issue by lordwhizy** [Kademi/keditor#195] opened 2019-07-28 00:34 UTC
When you click on preview button to remove the outlines in Iframe mode, only the content-area is shown in the preview, instead of the entire iframe. 
This makes the page look broken.

**Comment by ducdhm** [comment] 2019-07-28 09:47
@lordwhizy I dont get what you mean? Can you give me more details? Maybe some screenshot?

**Comment by ducdhm** [comment] 2019-07-30 01:45
Hi @lordwhizy,
Seem like I got what you mean. And in KEditor, when you're previewing, we still need to keep the topbar visible for some users' actions like Save, Fullscreen mode, Preview OFF, change device, etc...

It's KEditor's feature, not a bug. So I'll close this issue. If you have better idea, please create a "Request Feature" issue. Thanks for your contribution.

/Duc

**Closed by ducdhm** 2019-07-30 01:45 UTC
Labels: bug, question
